# settings
leader_key = "f18"        # required, the leader key that starts the sequence
leader_key_mods = ""      # optional, default "", not recommended - a dedicated leader key is better
                             # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = false    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps

s = ["raycast://extensions/raycast/navigation/switch-windows", "Switch Windows"]

[a]
label = "Applications"
b = ["/Applications/Zen.app", "Browser"]
e = ["/Applications/Zed.app", "Editor"]
f = ["/System/Library/CoreServices/Finder.app", "Finder"]
i = ["/System/Volumes/Data/Applications/IntelliJ IDEA.app", "Idea"]
s = ["/Applications/Slack.app", "Slack"]
t = ["/Applications/Ghostty.app", "Terminal"]
y = ["/Applications/Things3.app", "Things"]
z = ["/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app", "Safari"]

[b]
label = "Browser"
b = ["raycast://extensions/Keyruu/zen-browser/search-bookmarks", "Bookmarks"]
h = ["raycast://extensions/Keyruu/zen-browser/search-history", "History"]

[r]
label = "Raycast"
c = ["raycast://extensions/raycast/clipboard-history/clipboard-history", "Clipboard"]
e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "Emoji"]
k = ["raycast://extensions/rolandleth/kill-process/index", "Kill Process"]
n = ["raycast://extensions/raycast/apple-notes/index", "Notes"]
s = ["raycast://extensions/raycast/snippets/search-snippets", "Snippets"]
w = ["raycast://extensions/raycast/dictionary/define-word", "Word"]
C = ["raycast://extensions/raycast/raycast/confetti", "Confetti"]
R = "reload"
W = ["raycast://extensions/tonka3000/weather/index", "Weather"]

[t]
label = "Things"
a = ["cmd:shortcuts run 'Things Anytime'", "Anytime"]
i = ["cmd:shortcuts run 'Things Inbox'", "Inbox"]
q = ["cmd:shortcuts run 'QT'", "Quick Todo"]
t = ["cmd:shortcuts run 'Things Today'", "Today"]
u = ["cmd:shortcuts run 'Things Upcoming'", "Upcoming"]
