theme = "tokyonight"

[editor]
completion-timeout = 5
idle-timeout = 50
mouse = true
auto-save = true
cursorline = false
bufferline = "always"
color-modes	= true
# line-number = "relative"
rainbow-brackets = true
# rulers = [120]
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"
auto-format = true
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
auto-document-highlight = true
display-inlay-hints = false
display-progress-messages = true

[editor.soft-wrap]
enable = true
#wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "warning"

[editor.statusline]
left = [ "mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control", "diagnostics" ]
right = [ "primary-selection-length", "register", "position", "position-percentage", "total-line-numbers", "file-encoding" ]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space.g]
c = "changed_file_picker"
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
f = [":write-all", ":insert-output scooter --no-stdin >/dev/tty", ":redraw", ":reload-all"]
n = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
