notes_dir = "/Users/bharat/Library/Mobile Documents/com~apple~CloudDocs/ekphos"
journal_folder = "journal"
welcome_shown = false
theme = "ekphos-dawn"
show_empty_dir = true
syntax_theme = "base16-ocean.dark"
sidebar_collapsed = false
outline_collapsed = false
folders_first = true
frontmatter_hidden = true
show_tags = true
check_updates = true
transparent_bg = false
floating_cursor = false

[editor]
line_wrap = true
tab_width = 4
left_padding = 0
right_padding = 1
line_numbers = "absolute"
scrolloff = 0
