# Catppuccin Mocha Color Palette (dark variant of themes/catppuccin-mocha-custom.theme)
set -l foreground cdd6f4
set -l selection 313244
set -l comment 7f849c
set -l red f38ba8
set -l orange fab387
set -l yellow f9e2af
set -l green a6e3a1
set -l purple f2cdcd
set -l cyan 94e2d5
set -l pink cba6f7

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command 89b4fa
set -g fish_color_keyword $pink
set -g fish_color_quote $green
set -g fish_color_redirection f5c2e7
set -g fish_color_end $orange
set -g fish_color_option $green
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator f5c2e7
set -g fish_color_escape eba0ac
set -g fish_color_autosuggestion 6c7086
set -g fish_color_cancel $red
set -g fish_color_gray 6c7086
set -g fish_color_cwd $yellow
set -g fish_color_user $cyan
set -g fish_color_host 89b4fa
set -g fish_color_host_remote $green
set -g fish_color_status $red

# Completion Pager Colors
set -g fish_pager_color_progress 6c7086
set -g fish_pager_color_prefix f5c2e7
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description 6c7086
set -g fish_pager_color_selected_background --background=$selection
